apiVersion: v1
kind: Service
metadata:
  name: javawebapplivesvc 
spec:
  type: NodePort
  selector:
    version: v1 # v1 to v2   
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30787
...